
spring.datasource.url=jdbc:sqlserver://sqlserver-cp04-devops.database.windows.net:1433;database=cp04DB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
spring.datasource.username=cp04admin@sqlserver-cp04-devops
spring.datasource.password=Cp04@2025Secure
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


server.port=8080


azure.application-insights.connection-string=InstrumentationKey=83ccbdea-cc0f-4f5a-8fd5-5c981b323510;IngestionEndpoint=https://eastus2-3.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus2.livediagnostics.monitor.azure.com/;ApplicationId=46199884-15e7-4627-b4f8-bacedefa7be9


spring.application.name=PokemonFiap

