spring.datasource.url=jdbc:sqlserver://sqlserver-pokemonfiap-945-sprint3.database.windows.net:1433;databaseName=pokemonfiapDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
spring.datasource.username=Trainer@sqlserver-pokemonfiap-945-sprint3
spring.datasource.password=Azurecast@666
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


server.port=8080


spring.application.name=PokemonFiap

